# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  #config.vbguest.auto_update = false
  hosts = [ { name: 'master',  box:'centos/7' } ]
  hosts.each do |host|
    config.vm.define host[:name] do |node|
      node.vm.hostname = host[:name]
      node.vm.box = host[:box]
      node.vm.network "public_network"


      node.vm.provider :virtualbox do |vb|
          vb.name = host[:name]
      end
    end
  end
end
